// Validates the `insights` block of POST /api/meetings/upload-processed's
// body (see src/server/app.ts) — insights generated by a local Claude Code
// session instead of extractInsights.ts's schema-enforced tool-use call, so
// there's no equivalent guarantee the shape is well-formed on arrival.
//
// The wire shape deliberately omits `approved` entirely (the caller has no
// business setting it) — this module stamps the same invariants
// extractInsights.ts always has: takeaways auto-approved, actionItems/
// followUps not, since those are suggest-then-approve pending a human's
// review on the meeting detail page.

import type { ActionItem, FollowUpItem, SuggestionItem, Urgency } from "../../db/schema";
import type { ExtractInsightsResult } from "../pipeline/extractInsights";

export interface ProcessedInsightsInput {
  keywords?: unknown;
  takeaways?: unknown;
  actionItems?: unknown;
  followUps?: unknown;
}

const URGENCIES: Urgency[] = ["high", "medium", "low"];

function fail(message: string): never {
  throw new Error(`Invalid insights payload: ${message}`);
}

function asStringArray(value: unknown, label: string): string[] {
  if (!Array.isArray(value)) fail(`"${label}" must be an array.`);
  return value.map((v, i) => {
    if (typeof v !== "string" || !v.trim()) fail(`"${label}[${i}]" must be a non-empty string.`);
    return v;
  });
}

function asUrgency(value: unknown, label: string): Urgency {
  if (typeof value !== "string" || !URGENCIES.includes(value as Urgency)) {
    fail(`"${label}" must be one of ${URGENCIES.join("/")}, got: ${JSON.stringify(value)}.`);
  }
  return value as Urgency;
}

/** Throws with a descriptive message on any shape mismatch. */
export function validateProcessedInsights(input: ProcessedInsightsInput): ExtractInsightsResult {
  const keywords = asStringArray(input.keywords, "keywords");

  if (!Array.isArray(input.takeaways)) fail('"takeaways" must be an array.');
  const takeaways: SuggestionItem[] = input.takeaways.map((raw, i) => {
    if (typeof raw !== "object" || raw === null || typeof (raw as { text?: unknown }).text !== "string") {
      fail(`"takeaways[${i}]" must be an object with a string "text".`);
    }
    return { text: (raw as { text: string }).text, approved: true };
  });

  if (!Array.isArray(input.actionItems)) fail('"actionItems" must be an array.');
  const actionItems: ActionItem[] = input.actionItems.map((raw, i) => {
    if (typeof raw !== "object" || raw === null) fail(`"actionItems[${i}]" must be an object.`);
    const item = raw as { text?: unknown; urgency?: unknown };
    if (typeof item.text !== "string" || !item.text.trim()) {
      fail(`"actionItems[${i}].text" must be a non-empty string.`);
    }
    return { text: item.text, urgency: asUrgency(item.urgency, `actionItems[${i}].urgency`), approved: false };
  });

  if (!Array.isArray(input.followUps)) fail('"followUps" must be an array.');
  const followUps: FollowUpItem[] = input.followUps.map((raw, i) => {
    if (typeof raw !== "object" || raw === null) fail(`"followUps[${i}]" must be an object.`);
    const item = raw as { text?: unknown; person?: unknown; urgency?: unknown };
    if (typeof item.text !== "string" || !item.text.trim()) {
      fail(`"followUps[${i}].text" must be a non-empty string.`);
    }
    if (item.person !== null && typeof item.person !== "string") {
      fail(`"followUps[${i}].person" must be a string or null.`);
    }
    return {
      text: item.text,
      person: item.person,
      urgency: asUrgency(item.urgency, `followUps[${i}].urgency`),
      approved: false,
    };
  });

  return { keywords, takeaways, actionItems, followUps };
}
