#!/bin/bash
# Wrapper around the headless process-transcripts skill invocation — one
# single scan-and-process pass. Called repeatedly by scan-folder-loop.sh
# (every 20 minutes), which is itself started inside a real Terminal window
# by the GoodWrapScanFolder login item — NOT by launchd directly.
#
# History: this used to be invoked straight from a launchd LaunchAgent
# (com.goodwrap.scanfolder.plist). That was retired 2026-07-23 after
# extensive testing showed launchd-spawned headless processes on this Mac
# have flaky, intermittent access to files under ~/Documents (repeated
# `getcwd: cannot access parent directories: Operation not permitted`
# crashes, inconsistent even after granting the relevant binaries Full Disk
# Access) — while the exact same command run inside an interactive Terminal
# session always worked. Rather than keep chasing that OS-level quirk,
# scan-folder-loop.sh now runs this on the same cadence from inside a real
# Terminal window instead of a background daemon. See that script and
# scan-folder-terminal-launcher.applescript for the rest of the mechanism.
#
# Why the ALERT/OK line at the end exists: the skill's own final-turn
# summary is free-text generated by the model, and past runs have shown it
# isn't always trustworthy — multiple recorded runs claimed "nothing to do"
# / "already processed" while narrating things like "earlier in this
# session" that can't be true (each `claude -p` call is a fresh, isolated
# session per Anthropic's own docs, see https://code.claude.com/docs/en/
# headless.md — there is no earlier-in-this-session for a print-mode call).
# Rather than trust that narrative, this script independently re-checks the
# real, deterministic state of the watch folder after the skill exits and
# appends an unambiguous ALERT/OK line that a human (or a future monitoring
# check) can grep for, instead of having to read prose to figure out
# whether the run actually did anything.
#
# --no-session-persistence: real, documented flag (Claude Code CLI reference)
# — disables session save/resume for this one-shot print-mode call, so there
# is no session file to ever bloat or get resumed by accident. Deliberately
# NOT using --bare here even though Anthropic recommends it for scripted
# calls generally: --bare skips auto-discovery of skills, and this job's
# entire purpose is invoking the process-transcripts skill by name.

set -uo pipefail
cd "$(dirname "$0")/.."

MARKER="[scan-folder-job]"

/Users/peterdrummond/.npm-global/bin/claude -p \
  "Use the process-transcripts skill to scan the transcript watch folder and process any new files." \
  --dangerously-skip-permissions \
  --no-session-persistence
CLAUDE_EXIT=$?

REMAINING_JSON="$(npm run scan-folder -- list 2>/dev/null | tail -1)"
REMAINING_COUNT="$(echo "$REMAINING_JSON" | python3 -c 'import json,sys; print(len(json.load(sys.stdin)))' 2>/dev/null)"

echo
if [ "$CLAUDE_EXIT" -ne 0 ]; then
  echo "$MARKER ALERT: claude exited $CLAUDE_EXIT — check for auth/permission issues (e.g. a recent reboot, expired login, or Full Disk Access being revoked for the claude binary)."
elif [ -z "$REMAINING_COUNT" ]; then
  echo "$MARKER ALERT: couldn't verify remaining candidate count (scan-folder -- list didn't return parseable JSON): $REMAINING_JSON"
elif [ "$REMAINING_COUNT" != "0" ]; then
  echo "$MARKER ALERT: $REMAINING_COUNT file(s) still unprocessed after this run despite claude exiting 0: $REMAINING_JSON"
else
  echo "$MARKER OK: 0 files pending, claude exited 0."
fi
